# Generated by Django 4.2.4 on 2023-08-14 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swrs_org_id', models.IntegerField()),
                ('business_legal_name', models.CharField(max_length=1000)),
                ('english_trade_name', models.CharField(max_length=1000)),
                ('french_trade_name', models.CharField(max_length=1000)),
                ('cra_business_number', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('user_guid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=1000)),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reg.operator')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reg.user')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swrs_facility_id', models.IntegerField()),
                ('facility_name', models.CharField(max_length=1000)),
                ('facility_type', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.operator')),
            ],
        ),
    ]
