# Generated by Django 4.2.4 on 2023-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_userorganization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=50),
        ),
    ]
