# Generated by Django 4.2.4 on 2023-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
